// Generated by scripts/fetch-breed-photos.mjs. Do not edit by hand.
// Breed photos from Wikipedia / Wikimedia Commons; see CREDITS.md.
export const BREED_PHOTOS = {
  "affenpinscher": {
    "thumb": "images/breeds/affenpinscher-120.jpg",
    "photo": "images/breeds/affenpinscher-330.jpg",
    "author": "Unknown author",
    "license": "GPL",
    "source": "https://commons.wikimedia.org/wiki/File:Affenpinscher.jpg"
  },
  "afghan-hound": {
    "thumb": "images/breeds/afghan-hound-120.jpg",
    "photo": "images/breeds/afghan-hound-330.jpg",
    "author": "Weaveravel",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Afghan_dog_-_cropped.jpg"
  },
  "airedale-terrier": {
    "thumb": "images/breeds/airedale-terrier-120.jpg",
    "photo": "images/breeds/airedale-terrier-330.jpg",
    "author": "by",
    "license": "Copyrighted free use",
    "source": "https://commons.wikimedia.org/wiki/File:Airedale_Terrier.jpg"
  },
  "akita": {
    "thumb": "images/breeds/akita-120.jpg",
    "photo": "images/breeds/akita-330.jpg",
    "author": "Azurfrog",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Akita_Inu_(male).jpg"
  },
  "alaskan-malamute": {
    "thumb": "images/breeds/alaskan-malamute-120.jpg",
    "photo": "images/breeds/alaskan-malamute-330.jpg",
    "author": "SCMW",
    "license": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Alaskan_Malamute.jpg"
  },
  "american-eskimo-dog": {
    "thumb": "images/breeds/american-eskimo-dog-120.jpg",
    "photo": "images/breeds/american-eskimo-dog-330.jpg",
    "author": "Christmas w/a K",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:American_Eskimo_Dog_1.jpg"
  },
  "american-foxhound": {
    "thumb": "images/breeds/american-foxhound-120.jpg",
    "photo": "images/breeds/american-foxhound-330.jpg",
    "author": "Unknown author",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:AmericanFoxhound2.jpg"
  },
  "american-pit-bull-terrier": {
    "thumb": "images/breeds/american-pit-bull-terrier-120.jpg",
    "photo": "images/breeds/american-pit-bull-terrier-330.jpg",
    "author": "geoggirl on Flickr",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:001_American_Pit_Bull_Terrier.jpg"
  },
  "american-staffordshire-terrier": {
    "thumb": "images/breeds/american-staffordshire-terrier-120.jpg",
    "photo": "images/breeds/american-staffordshire-terrier-330.jpg",
    "author": "Svenska Mässan from Sweden",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:AMERICAN_STAFFORDSHIRE_TERRIER,_Zican%E2%80%99s_Bz_Ez_Dragon_(24208348891).2.jpg"
  },
  "anatolian-shepherd": {
    "thumb": "images/breeds/anatolian-shepherd-120.jpg",
    "photo": "images/breeds/anatolian-shepherd-330.jpg",
    "author": "Kangalshepherddog",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Kangal_front_on.jpg"
  },
  "australian-cattle-dog": {
    "thumb": "images/breeds/australian-cattle-dog-120.jpg",
    "photo": "images/breeds/australian-cattle-dog-330.jpg",
    "author": "Zingpix",
    "license": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:ACD-blue-spud.jpg"
  },
  "australian-shepherd": {
    "thumb": "images/breeds/australian-shepherd-120.jpg",
    "photo": "images/breeds/australian-shepherd-330.jpg",
    "author": "Trickdog-Fina",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Australian_Shepherd_red_bi.JPG"
  },
  "australian-terrier": {
    "thumb": "images/breeds/australian-terrier-120.jpg",
    "photo": "images/breeds/australian-terrier-330.jpg",
    "author": "Chuck in MA",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Australian_Terrier_adult_male.jpg"
  },
  "basenji": {
    "thumb": "images/breeds/basenji-120.jpg",
    "photo": "images/breeds/basenji-330.jpg",
    "author": "fugzu",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Basenji_Profile_(loosercrop).jpg"
  },
  "basset-hound": {
    "thumb": "images/breeds/basset-hound-120.jpg",
    "photo": "images/breeds/basset-hound-330.jpg",
    "author": "Cali1008",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:BassetHound_profil.jpg"
  },
  "beagle": {
    "thumb": "images/breeds/beagle-120.jpg",
    "photo": "images/breeds/beagle-330.jpg",
    "author": "Unknown author",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Beagle_600.jpg"
  },
  "bearded-collie": {
    "thumb": "images/breeds/bearded-collie-120.jpg",
    "photo": "images/breeds/bearded-collie-330.jpg",
    "author": "Unknown author",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bearded_Collie_600.jpg"
  },
  "bedlington-terrier": {
    "thumb": "images/breeds/bedlington-terrier-120.jpg",
    "photo": "images/breeds/bedlington-terrier-330.jpg",
    "author": "David Owsiany",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Boutchie_apres_championnat_004.JPG"
  },
  "belgian-malinois": {
    "thumb": "images/breeds/belgian-malinois-120.jpg",
    "photo": "images/breeds/belgian-malinois-330.jpg",
    "author": "Canarian",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Malinois_Shepherd3.JPG"
  },
  "belgian-tervuren": {
    "thumb": "images/breeds/belgian-tervuren-120.jpg",
    "photo": "images/breeds/belgian-tervuren-330.jpg",
    "author": "Patty Carlson",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tervuren.jpg"
  },
  "bernese-mountain-dog": {
    "thumb": "images/breeds/bernese-mountain-dog-120.jpg",
    "photo": "images/breeds/bernese-mountain-dog-330.jpg",
    "author": "FriendlyToaster",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:3-BerneseMountainDogInGrass.jpg"
  },
  "bichon-frise": {
    "thumb": "images/breeds/bichon-frise-120.jpg",
    "photo": "images/breeds/bichon-frise-330.jpg",
    "author": "Heike Andres",
    "license": "CC BY-SA 3.0 de",
    "source": "https://commons.wikimedia.org/wiki/File:Bichon_Fris%C3%A9_-_studdogbichon.jpg"
  },
  "black-and-tan-coonhound": {
    "thumb": "images/breeds/black-and-tan-coonhound-120.jpg",
    "photo": "images/breeds/black-and-tan-coonhound-330.jpg",
    "author": "Steffen Heinz (Caronna)",
    "license": "CC BY-SA 2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Black_and_Tan_Coonhound.jpg"
  },
  "bloodhound": {
    "thumb": "images/breeds/bloodhound-120.jpg",
    "photo": "images/breeds/bloodhound-330.jpg",
    "author": "User:Erland22",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bloodhound_Erland22.jpg"
  },
  "bluetick-coonhound": {
    "thumb": "images/breeds/bluetick-coonhound-120.jpg",
    "photo": "images/breeds/bluetick-coonhound-330.jpg",
    "author": "Unknown author",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:BluetickCoonhound.jpg"
  },
  "border-collie": {
    "thumb": "images/breeds/border-collie-120.jpg",
    "photo": "images/breeds/border-collie-330.jpg",
    "author": "Unknown author",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Border_Collie_600.jpg"
  },
  "border-terrier": {
    "thumb": "images/breeds/border-terrier-120.jpg",
    "photo": "images/breeds/border-terrier-330.jpg",
    "author": "Unknown author",
    "license": "GPL",
    "source": "https://commons.wikimedia.org/wiki/File:Border_Terrier.jpg"
  },
  "borzoi": {
    "thumb": "images/breeds/borzoi-120.jpg",
    "photo": "images/breeds/borzoi-330.jpg",
    "author": "Pleple2000",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Chart_rosyjski_borzoj_rybnik-kamien_pl.jpg"
  },
  "boston-terrier": {
    "thumb": "images/breeds/boston-terrier-120.jpg",
    "photo": "images/breeds/boston-terrier-330.jpg",
    "author": "Andreas Schlaugat",
    "license": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Boston-terrier-carlos-de.JPG"
  },
  "bouvier-des-flandres": {
    "thumb": "images/breeds/bouvier-des-flandres-120.jpg",
    "photo": "images/breeds/bouvier-des-flandres-330.jpg",
    "author": "Basco at Dutch Wikipedia",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bouvier.JPG"
  },
  "boxer": {
    "thumb": "images/breeds/boxer-120.jpg",
    "photo": "images/breeds/boxer-330.jpg",
    "author": "Mood210",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Male_fawn_Boxer_undocked.jpg"
  },
  "briard": {
    "thumb": "images/breeds/briard-120.jpg",
    "photo": "images/breeds/briard-330.jpg",
    "author": "Birgit Balzer, Deutschland",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Briard_fauve.JPG"
  },
  "brittany": {
    "thumb": "images/breeds/brittany-120.jpg",
    "photo": "images/breeds/brittany-330.jpg",
    "author": "Olatz / souligne",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Zuri_txakurra_1_(cropped).JPG"
  },
  "brussels-griffon": {
    "thumb": "images/breeds/brussels-griffon-120.jpg",
    "photo": "images/breeds/brussels-griffon-330.jpg",
    "author": "Arne Fagerholt",
    "license": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Monkey_Bizniz_Drama_Queen.jpg"
  },
  "bull-terrier": {
    "thumb": "images/breeds/bull-terrier-120.jpg",
    "photo": "images/breeds/bull-terrier-330.jpg",
    "author": "Pixabay User TC-TORRES",
    "license": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Bullterrier-3453301920.jpg"
  },
  "bulldog": {
    "thumb": "images/breeds/bulldog-120.jpg",
    "photo": "images/breeds/bulldog-330.jpg",
    "author": "Av3553 at English Wikipedia",
    "license": "GFDL",
    "source": "https://commons.wikimedia.org/wiki/File:Whitebulldog.jpg"
  },
  "bullmastiff": {
    "thumb": "images/breeds/bullmastiff-120.jpg",
    "photo": "images/breeds/bullmastiff-330.jpg",
    "author": "Fausto Moreno",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bullmastiff_edited.JPG"
  },
  "cairn-terrier": {
    "thumb": "images/breeds/cairn-terrier-120.jpg",
    "photo": "images/breeds/cairn-terrier-330.jpg",
    "author": "Ronald Müller-Hagen (Ketterechts)",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cairn-Terrier-Garten1.jpg"
  },
  "cane-corso": {
    "thumb": "images/breeds/cane-corso-120.jpg",
    "photo": "images/breeds/cane-corso-330.jpg",
    "author": "Claudio Domiziani",
    "license": "CC BY-SA 2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Cane_corso_temi_1_1024x768x24_(cropped).png"
  },
  "cardigan-welsh-corgi": {
    "thumb": "images/breeds/cardigan-welsh-corgi-120.jpg",
    "photo": "images/breeds/cardigan-welsh-corgi-330.jpg",
    "author": "FatFairfax",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cardigan_Welsh_Corgi,_Profile.png"
  },
  "catahoula-leopard-dog": {
    "thumb": "images/breeds/catahoula-leopard-dog-120.jpg",
    "photo": "images/breeds/catahoula-leopard-dog-330.jpg",
    "author": "Nagygabornet",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:02._Coahoma_Arkansas_Logan.jpg"
  },
  "cavalier-king-charles-spaniel": {
    "thumb": "images/breeds/cavalier-king-charles-spaniel-120.jpg",
    "photo": "images/breeds/cavalier-king-charles-spaniel-330.jpg",
    "author": "Andreweatock",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:CarterBIS.Tiki.13.6.09.jpg"
  },
  "chesapeake-bay-retriever": {
    "thumb": "images/breeds/chesapeake-bay-retriever-120.jpg",
    "photo": "images/breeds/chesapeake-bay-retriever-330.jpg",
    "author": "George Makatura",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:CH_Chesapeake.jpg"
  },
  "chihuahua": {
    "thumb": "images/breeds/chihuahua-120.jpg",
    "photo": "images/breeds/chihuahua-330.jpg",
    "author": "Bonnie van den Born",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Chihuahua1_bvdb.jpg"
  },
  "chinese-crested": {
    "thumb": "images/breeds/chinese-crested-120.jpg",
    "photo": "images/breeds/chinese-crested-330.jpg",
    "author": "Tommy Gildseth",
    "license": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:IndyStands.jpg"
  },
  "chow-chow": {
    "thumb": "images/breeds/chow-chow-120.jpg",
    "photo": "images/breeds/chow-chow-330.jpg",
    "author": "Томасина",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Chow-chow_in_Tallinn.JPG"
  },
  "cocker-spaniel": {
    "thumb": "images/breeds/cocker-spaniel-120.jpg",
    "photo": "images/breeds/cocker-spaniel-330.jpg",
    "author": "Kulala",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:PointbreakHoneyimHome.jpg"
  },
  "dachshund": {
    "thumb": "images/breeds/dachshund-120.jpg",
    "photo": "images/breeds/dachshund-330.jpg",
    "author": "Katemil94",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:%EB%8B%A5%EC%8A%A4%ED%9B%88%ED%8A%B8(%EB%8B%A8%EB%AA%A8%EC%A2%85)_(Dachshund_(Short)).jpg"
  },
  "dalmatian": {
    "thumb": "images/breeds/dalmatian-120.jpg",
    "photo": "images/breeds/dalmatian-330.jpg",
    "author": "Bradlien",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Sun_Dog_Dalmatian.jpg"
  },
  "doberman-pinscher": {
    "thumb": "images/breeds/doberman-pinscher-120.jpg",
    "photo": "images/breeds/doberman-pinscher-330.jpg",
    "author": "Miroslav Cacik",
    "license": "Copyrighted free use",
    "source": "https://commons.wikimedia.org/wiki/File:Dobermann_handling.jpg"
  },
  "dogue-de-bordeaux": {
    "thumb": "images/breeds/dogue-de-bordeaux-120.jpg",
    "photo": "images/breeds/dogue-de-bordeaux-330.jpg",
    "author": "Canarian",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:French_Mastiff_female_4.jpg"
  },
  "english-cocker-spaniel": {
    "thumb": "images/breeds/english-cocker-spaniel-120.jpg",
    "photo": "images/breeds/english-cocker-spaniel-330.jpg",
    "author": "Jean-Pol GRANDMONT",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:%22Bill%22_-_Cocker_spaniel_anglais_2.JPG"
  },
  "english-pointer": {
    "thumb": "images/breeds/english-pointer-120.jpg",
    "photo": "images/breeds/english-pointer-330.jpg",
    "author": "Canarian",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:English_Pointer_orange-white.jpg"
  },
  "english-setter": {
    "thumb": "images/breeds/english-setter-120.jpg",
    "photo": "images/breeds/english-setter-330.jpg",
    "author": "Elf at English Wikipedia",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:EnglishSetter9_fx_wb.jpg"
  },
  "english-springer-spaniel": {
    "thumb": "images/breeds/english-springer-spaniel-120.jpg",
    "photo": "images/breeds/english-springer-spaniel-330.jpg",
    "author": "Ratsniffer",
    "license": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Springer_Spaniel_Wide_Shot.jpg"
  },
  "field-spaniel": {
    "thumb": "images/breeds/field-spaniel-120.jpg",
    "photo": "images/breeds/field-spaniel-330.jpg",
    "author": "Pleple2000",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Field_spaniel_581.jpg"
  },
  "flat-coated-retriever": {
    "thumb": "images/breeds/flat-coated-retriever-120.jpg",
    "photo": "images/breeds/flat-coated-retriever-330.jpg",
    "author": "Gunnandreassen",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Flat_Coated_Retriever_-_black.jpg"
  },
  "french-bulldog": {
    "thumb": "images/breeds/french-bulldog-120.jpg",
    "photo": "images/breeds/french-bulldog-330.jpg",
    "author": "Ildar Sagdejev (Specious)",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:2008-07-28_Dog_at_Frolick_Field.jpg"
  },
  "german-shepherd": {
    "thumb": "images/breeds/german-shepherd-120.jpg",
    "photo": "images/breeds/german-shepherd-330.jpg",
    "author": "gomagoti",
    "license": "CC BY-SA 2.5",
    "source": "https://commons.wikimedia.org/wiki/File:German_Shepherd_-_DSC_0346_(10096362833).jpg"
  },
  "german-shorthaired-pointer": {
    "thumb": "images/breeds/german-shorthaired-pointer-120.jpg",
    "photo": "images/breeds/german-shorthaired-pointer-330.jpg",
    "author": "Bonnie van den Born",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Duitse_staande_korthaar_10-10-2.jpg"
  },
  "german-wirehaired-pointer": {
    "thumb": "images/breeds/german-wirehaired-pointer-120.jpg",
    "photo": "images/breeds/german-wirehaired-pointer-330.jpg",
    "author": "JainaKo",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Dan_vom_hardenberg_(cropped).jpg"
  },
  "giant-schnauzer": {
    "thumb": "images/breeds/giant-schnauzer-120.jpg",
    "photo": "images/breeds/giant-schnauzer-330.jpg",
    "author": "Petrucha",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Nev_Lemar_Barbara1.jpg"
  },
  "golden-retriever": {
    "thumb": "images/breeds/golden-retriever-120.jpg",
    "photo": "images/breeds/golden-retriever-330.jpg",
    "author": "Janneke Vreugdenhil; derivative work: Anka Friedrich",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Golden_Retriever_Dukedestiny01_drvd.jpg"
  },
  "gordon-setter": {
    "thumb": "images/breeds/gordon-setter-120.jpg",
    "photo": "images/breeds/gordon-setter-330.jpg",
    "author": "Unknown author",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Orrvilas_enska_w800px.jpg"
  },
  "great-dane": {
    "thumb": "images/breeds/great-dane-120.jpg",
    "photo": "images/breeds/great-dane-330.jpg",
    "author": "Lilly M",
    "license": "CC BY-SA 2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Dog_niemiecki_%C5%BC%C3%B3%C5%82ty_LM980.jpg"
  },
  "great-pyrenees": {
    "thumb": "images/breeds/great-pyrenees-120.jpg",
    "photo": "images/breeds/great-pyrenees-330.jpg",
    "author": "HeartSpoon",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Great_Pyrenees_Mountain_Dog_2.png"
  },
  "greater-swiss-mountain-dog": {
    "thumb": "images/breeds/greater-swiss-mountain-dog-120.jpg",
    "photo": "images/breeds/greater-swiss-mountain-dog-330.jpg",
    "author": "Canarian",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Greater_Swiss_Mountain_Dog_2018.jpg"
  },
  "greyhound": {
    "thumb": "images/breeds/greyhound-120.jpg",
    "photo": "images/breeds/greyhound-330.jpg",
    "author": "Neurodoc",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:GraceTheGreyhound.jpg"
  },
  "havanese": {
    "thumb": "images/breeds/havanese-120.jpg",
    "photo": "images/breeds/havanese-330.jpg",
    "author": "audrey_sel",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:A_Havanese_judging.jpg"
  },
  "icelandic-sheepdog": {
    "thumb": "images/breeds/icelandic-sheepdog-120.jpg",
    "photo": "images/breeds/icelandic-sheepdog-330.jpg",
    "author": "Veronica Druk",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Icelandic_Sheepdog_Alisa_von_Lehenberg.jpg"
  },
  "irish-setter": {
    "thumb": "images/breeds/irish-setter-120.jpg",
    "photo": "images/breeds/irish-setter-330.jpg",
    "author": "Luis Miguel Bugallo Sánchez (Lmbuga Galipedia)",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Can_Setter_dog_GFDL.jpg"
  },
  "irish-wolfhound": {
    "thumb": "images/breeds/irish-wolfhound-120.jpg",
    "photo": "images/breeds/irish-wolfhound-330.jpg",
    "author": "Dux",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:(2)_Irish_Wolfhound_4.jpg"
  },
  "italian-greyhound": {
    "thumb": "images/breeds/italian-greyhound-120.jpg",
    "photo": "images/breeds/italian-greyhound-330.jpg",
    "author": "christina",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Italian_Greyhound_standing_gray_(cropped).jpg"
  },
  "jack-russell-terrier": {
    "thumb": "images/breeds/jack-russell-terrier-120.jpg",
    "photo": "images/breeds/jack-russell-terrier-330.jpg",
    "author": "Plank",
    "license": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Jack_Russell_Terrier_1.jpg"
  },
  "japanese-chin": {
    "thumb": "images/breeds/japanese-chin-120.jpg",
    "photo": "images/breeds/japanese-chin-330.jpg",
    "author": "Joliot",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Chin_posing.jpg"
  },
  "keeshond": {
    "thumb": "images/breeds/keeshond-120.jpg",
    "photo": "images/breeds/keeshond-330.jpg",
    "author": "dancing with wolves",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Keeshond_Majic_standing_cropped.jpg"
  },
  "kerry-blue-terrier": {
    "thumb": "images/breeds/kerry-blue-terrier-120.jpg",
    "photo": "images/breeds/kerry-blue-terrier-330.jpg",
    "author": "Peter Kumpert, Germany",
    "license": "CC BY-SA 3.0 de",
    "source": "https://commons.wikimedia.org/wiki/File:Kerry_Blue_Terrier.jpg"
  },
  "kuvasz": {
    "thumb": "images/breeds/kuvasz-120.jpg",
    "photo": "images/breeds/kuvasz-330.jpg",
    "author": "Erdelyi kopo",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Kuvasz_named_Kan.jpg"
  },
  "labrador-retriever": {
    "thumb": "images/breeds/labrador-retriever-120.jpg",
    "photo": "images/breeds/labrador-retriever-330.jpg",
    "author": "IDS.photos from Tiverton, UK",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Labrador_on_Quantock_(2175262184).jpg"
  },
  "lagotto-romagnolo": {
    "thumb": "images/breeds/lagotto-romagnolo-120.jpg",
    "photo": "images/breeds/lagotto-romagnolo-330.jpg",
    "author": "Entheta",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bellalagotto4.jpg"
  },
  "leonberger": {
    "thumb": "images/breeds/leonberger-120.jpg",
    "photo": "images/breeds/leonberger-330.jpg",
    "author": "Kurre92",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Leonberger_male.jpg"
  },
  "lhasa-apso": {
    "thumb": "images/breeds/lhasa-apso-120.jpg",
    "photo": "images/breeds/lhasa-apso-330.jpg",
    "author": "Elminjas at Dutch Wikipedia",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Aishia.jpg"
  },
  "maltese": {
    "thumb": "images/breeds/maltese-120.jpg",
    "photo": "images/breeds/maltese-330.jpg",
    "author": "Sannse",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Maltese_600.jpg"
  },
  "mastiff": {
    "thumb": "images/breeds/mastiff-120.jpg",
    "photo": "images/breeds/mastiff-330.jpg",
    "author": "Radovan Rohovsky",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Westgort_Anticipation_17_months.JPG"
  },
  "miniature-american-shepherd": {
    "thumb": "images/breeds/miniature-american-shepherd-120.jpg",
    "photo": "images/breeds/miniature-american-shepherd-330.jpg",
    "author": "Lextergrace",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Blue_Merle_Miniature_American_Shepherd_in_Grass.jpg"
  },
  "miniature-pinscher": {
    "thumb": "images/breeds/miniature-pinscher-120.jpg",
    "photo": "images/breeds/miniature-pinscher-330.jpg",
    "author": "Sebastian Wallin. Sebastian Wallin. Sebwal",
    "license": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Miniature_pinscher.jpg"
  },
  "miniature-poodle": {
    "thumb": "images/breeds/miniature-poodle-120.jpg",
    "photo": "images/breeds/miniature-poodle-330.jpg",
    "author": "Tim Wilson from Blaine, MN, USA",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Full_attention_(8067543690).jpg"
  },
  "miniature-schnauzer": {
    "thumb": "images/breeds/miniature-schnauzer-120.jpg",
    "photo": "images/breeds/miniature-schnauzer-330.jpg",
    "author": "Canarian",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Miniature_Schnauzer_salt_%26_pepper_(cropped).jpg"
  },
  "neapolitan-mastiff": {
    "thumb": "images/breeds/neapolitan-mastiff-120.jpg",
    "photo": "images/breeds/neapolitan-mastiff-330.jpg",
    "author": "Bramans",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Neapolitan_Mastiff_(mastino_napoletano).jpg"
  },
  "newfoundland": {
    "thumb": "images/breeds/newfoundland-120.jpg",
    "photo": "images/breeds/newfoundland-330.jpg",
    "author": "Flickr user DanDee Shots",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Newfoundland_dog_Smoky.jpg"
  },
  "norwegian-elkhound": {
    "thumb": "images/breeds/norwegian-elkhound-120.jpg",
    "photo": "images/breeds/norwegian-elkhound-330.jpg",
    "author": "HawkNightingale175",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Elkhound2020_(cropped).jpg"
  },
  "norwich-terrier": {
    "thumb": "images/breeds/norwich-terrier-120.jpg",
    "photo": "images/breeds/norwich-terrier-330.jpg",
    "author": "H. Gisin",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Norwichterrier.jpg"
  },
  "nova-scotia-duck-tolling-retriever": {
    "thumb": "images/breeds/nova-scotia-duck-tolling-retriever-120.jpg",
    "photo": "images/breeds/nova-scotia-duck-tolling-retriever-330.jpg",
    "author": "Cal119 at English Wikipedia",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Duck_Toller.jpg"
  },
  "old-english-sheepdog": {
    "thumb": "images/breeds/old-english-sheepdog-120.jpg",
    "photo": "images/breeds/old-english-sheepdog-330.jpg",
    "author": "AKS.9955",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Old_English_Sheepdog_(side).jpg"
  },
  "papillon": {
    "thumb": "images/breeds/papillon-120.jpg",
    "photo": "images/breeds/papillon-330.jpg",
    "author": "Gvdmoort",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Outdoor_Continental_Toy_Spaniel_Papillon.jpeg"
  },
  "pekingese": {
    "thumb": "images/breeds/pekingese-120.jpg",
    "photo": "images/breeds/pekingese-330.jpg",
    "author": "SheltieBoy",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:1AKC_Pekingese_Dog_Show_2011.jpg"
  },
  "pembroke-welsh-corgi": {
    "thumb": "images/breeds/pembroke-welsh-corgi-120.jpg",
    "photo": "images/breeds/pembroke-welsh-corgi-330.jpg",
    "author": "Dog breed facts",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Welsh_Pembroke_Corgi.jpg"
  },
  "petit-basset-griffon-vendeen": {
    "thumb": "images/breeds/petit-basset-griffon-vendeen-120.jpg",
    "photo": "images/breeds/petit-basset-griffon-vendeen-330.jpg",
    "author": "Sannse",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:P_Basset_Griffon_Vendeen_600.jpg"
  },
  "pharaoh-hound": {
    "thumb": "images/breeds/pharaoh-hound-120.jpg",
    "photo": "images/breeds/pharaoh-hound-330.jpg",
    "author": "Pleple2000",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pies_faraona_e34.jpg"
  },
  "pomeranian": {
    "thumb": "images/breeds/pomeranian-120.jpg",
    "photo": "images/breeds/pomeranian-330.jpg",
    "author": "Blackoranges",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Pomeranian.JPG"
  },
  "poodle": {
    "thumb": "images/breeds/poodle-120.jpg",
    "photo": "images/breeds/poodle-330.jpg",
    "author": "Tim Wilson from Blaine, MN, USA",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Full_attention_(8067543690).jpg"
  },
  "portuguese-water-dog": {
    "thumb": "images/breeds/portuguese-water-dog-120.jpg",
    "photo": "images/breeds/portuguese-water-dog-330.jpg",
    "author": "Silke Hollje-Schumacher",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:C%C3%A3o_de_agua_Portugu%C3%AAs_2.jpg"
  },
  "pug": {
    "thumb": "images/breeds/pug-120.jpg",
    "photo": "images/breeds/pug-330.jpg",
    "author": "Xidrep",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Mops-duke-mopszucht-vom-maegdebrunnen.jpg"
  },
  "puli": {
    "thumb": "images/breeds/puli-120.jpg",
    "photo": "images/breeds/puli-330.jpg",
    "author": "Original uploader was Elf at en.wikipedia",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:PuliBlack_wb.jpg"
  },
  "rat-terrier": {
    "thumb": "images/breeds/rat-terrier-120.jpg",
    "photo": "images/breeds/rat-terrier-330.jpg",
    "author": "Jadenschaul",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Amberina_the_Rat_Terrier.jpg"
  },
  "redbone-coonhound": {
    "thumb": "images/breeds/redbone-coonhound-120.jpg",
    "photo": "images/breeds/redbone-coonhound-330.jpg",
    "author": "127177p",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Redbone-coonhound-detail.jpg"
  },
  "rhodesian-ridgeback": {
    "thumb": "images/breeds/rhodesian-ridgeback-120.jpg",
    "photo": "images/breeds/rhodesian-ridgeback-330.jpg",
    "author": "Bonnie van den Born",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Rhodesian_ridgeback.jpg"
  },
  "rottweiler": {
    "thumb": "images/breeds/rottweiler-120.jpg",
    "photo": "images/breeds/rottweiler-330.jpg",
    "author": "Dr. Manfred Herrmann Allgemeiner Deutscher Rottweiler-Klub (ADRK) e.V",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Rottweiler_standing_facing_left.jpg"
  },
  "rough-collie": {
    "thumb": "images/breeds/rough-collie-120.jpg",
    "photo": "images/breeds/rough-collie-330.jpg",
    "author": "Yasu w",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Rough-Collie-japan08_(cropped).jpg"
  },
  "saint-bernard": {
    "thumb": "images/breeds/saint-bernard-120.jpg",
    "photo": "images/breeds/saint-bernard-330.jpg",
    "author": "Blanky",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hummel_Vedor_vd_Robandahoeve.jpg"
  },
  "saluki": {
    "thumb": "images/breeds/saluki-120.jpg",
    "photo": "images/breeds/saluki-330.jpg",
    "author": "r",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Red_Smooth_Saluki.jpg"
  },
  "samoyed": {
    "thumb": "images/breeds/samoyed-120.jpg",
    "photo": "images/breeds/samoyed-330.jpg",
    "author": "Pleple2000",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Samojed00.jpg"
  },
  "schipperke": {
    "thumb": "images/breeds/schipperke-120.jpg",
    "photo": "images/breeds/schipperke-330.jpg",
    "author": "鏑木對馬守",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Schipperke0001.jpg"
  },
  "scottish-deerhound": {
    "thumb": "images/breeds/scottish-deerhound-120.jpg",
    "photo": "images/breeds/scottish-deerhound-330.jpg",
    "author": "Sisteskrik",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Karrie.JPG"
  },
  "scottish-terrier": {
    "thumb": "images/breeds/scottish-terrier-120.jpg",
    "photo": "images/breeds/scottish-terrier-330.jpg",
    "author": "Elise Carroll",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Scottish_Terrier_Photo_of_Face.jpg"
  },
  "shar-pei": {
    "thumb": "images/breeds/shar-pei-120.jpg",
    "photo": "images/breeds/shar-pei-330.jpg",
    "author": "Yan Mis/&Den Rakov",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Adult_sharpei.jpg"
  },
  "shetland-sheepdog": {
    "thumb": "images/breeds/shetland-sheepdog-120.jpg",
    "photo": "images/breeds/shetland-sheepdog-330.jpg",
    "author": "Flickr user nickobec (Nick Cowie)",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Shetland_Sheepdog_sable.jpg"
  },
  "shiba-inu": {
    "thumb": "images/breeds/shiba-inu-120.jpg",
    "photo": "images/breeds/shiba-inu-330.jpg",
    "author": "Takashiba at English Wikipedia",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Taka_Shiba.jpg"
  },
  "shih-tzu": {
    "thumb": "images/breeds/shih-tzu-120.jpg",
    "photo": "images/breeds/shih-tzu-330.jpg",
    "author": "Canino21",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Shihtzu_(cropped).jpg"
  },
  "siberian-husky": {
    "thumb": "images/breeds/siberian-husky-120.jpg",
    "photo": "images/breeds/siberian-husky-330.jpg",
    "author": "xJaM",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Husky_L.jpg"
  },
  "silky-terrier": {
    "thumb": "images/breeds/silky-terrier-120.jpg",
    "photo": "images/breeds/silky-terrier-330.jpg",
    "author": "Ofsilkysdream",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Australian_Silky_Terrier_Alana_Of_Silky%27s_Dream.jpg"
  },
  "sloughi": {
    "thumb": "images/breeds/sloughi-120.jpg",
    "photo": "images/breeds/sloughi-330.jpg",
    "author": "Denhulde",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Sloughi_male.jpg"
  },
  "soft-coated-wheaten-terrier": {
    "thumb": "images/breeds/soft-coated-wheaten-terrier-120.jpg",
    "photo": "images/breeds/soft-coated-wheaten-terrier-330.jpg",
    "author": "Terrierkännaren",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Soft-Coated_Wheaten_Terrier.jpg"
  },
  "spinone-italiano": {
    "thumb": "images/breeds/spinone-italiano-120.jpg",
    "photo": "images/breeds/spinone-italiano-330.jpg",
    "author": "Alephalpha",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:05042363_Spinone_braun.jpg"
  },
  "staffordshire-bull-terrier": {
    "thumb": "images/breeds/staffordshire-bull-terrier-120.jpg",
    "photo": "images/breeds/staffordshire-bull-terrier-330.jpg",
    "author": "Or Logassi",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:%D7%A1%D7%90%D7%98%D7%A3_%D7%90%D7%A0%D7%92%D7%9C%D7%99.jpg"
  },
  "standard-schnauzer": {
    "thumb": "images/breeds/standard-schnauzer-120.jpg",
    "photo": "images/breeds/standard-schnauzer-330.jpg",
    "author": "Tamorlan",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Standard_Grey_Schnauzer_(cropped).JPG"
  },
  "tibetan-mastiff": {
    "thumb": "images/breeds/tibetan-mastiff-120.jpg",
    "photo": "images/breeds/tibetan-mastiff-330.jpg",
    "author": "Svenska Mässan from Sweden",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:BIR_Grupp_2-_TIBETANSK_MASTIFF,_Legenda_Tibeta_Temudzhin_(23938629470).jpg"
  },
  "tibetan-terrier": {
    "thumb": "images/breeds/tibetan-terrier-120.jpg",
    "photo": "images/breeds/tibetan-terrier-330.jpg",
    "author": "Mr407SW",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Tibet_Terrier_Bennie_(cropped).jpg"
  },
  "toy-poodle": {
    "thumb": "images/breeds/toy-poodle-120.jpg",
    "photo": "images/breeds/toy-poodle-330.jpg",
    "author": "Tim Wilson from Blaine, MN, USA",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Full_attention_(8067543690).jpg"
  },
  "treeing-walker-coonhound": {
    "thumb": "images/breeds/treeing-walker-coonhound-120.jpg",
    "photo": "images/breeds/treeing-walker-coonhound-330.jpg",
    "author": "Kingkong954",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Treeing-walker-coonhound-standing.jpg"
  },
  "vizsla": {
    "thumb": "images/breeds/vizsla-120.jpg",
    "photo": "images/breeds/vizsla-330.jpg",
    "author": "Pleple2000",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Wy%C5%BCe%C5%82_w%C4%99gierski_g%C5%82adkow%C5%82osy_500.jpg"
  },
  "weimaraner": {
    "thumb": "images/breeds/weimaraner-120.jpg",
    "photo": "images/breeds/weimaraner-330.jpg",
    "author": "Rufus46",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Weimaraner_Freika-2.jpg"
  },
  "west-highland-white-terrier": {
    "thumb": "images/breeds/west-highland-white-terrier-120.jpg",
    "photo": "images/breeds/west-highland-white-terrier-330.jpg",
    "author": "Christopher Walker from Krakow, Poland",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:West_Highland_White_Terrier_Krakow.jpg"
  },
  "whippet": {
    "thumb": "images/breeds/whippet-120.jpg",
    "photo": "images/breeds/whippet-330.jpg",
    "author": "Canarian",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Whippet_2018_6.jpg"
  },
  "wire-fox-terrier": {
    "thumb": "images/breeds/wire-fox-terrier-120.jpg",
    "photo": "images/breeds/wire-fox-terrier-330.jpg",
    "author": "Simona Nováková, owner",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Elias1%C4%8Derven2006.jpg"
  },
  "wirehaired-pointing-griffon": {
    "thumb": "images/breeds/wirehaired-pointing-griffon-120.jpg",
    "photo": "images/breeds/wirehaired-pointing-griffon-330.jpg",
    "author": "CarolPtak",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:GCH_Int_Ch_UCH_Zerubbabel_von_Herrenhausen_CGC_MHA.jpg"
  },
  "xoloitzcuintli": {
    "thumb": "images/breeds/xoloitzcuintli-120.jpg",
    "photo": "images/breeds/xoloitzcuintli-330.jpg",
    "author": "Svenska Mässan from Sweden",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:BIR_Grupp_5-_MEXIKANSK_NAKENHUND,_Lokal_Hero%E2%80%99s_King_Og_Hart%E2%80%99s_Istas_(23607403303).jpg"
  },
  "yorkshire-terrier": {
    "thumb": "images/breeds/yorkshire-terrier-120.jpg",
    "photo": "images/breeds/yorkshire-terrier-330.jpg",
    "author": "Svenska Mässan from Sweden",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:(2_version)_Grupp_3,_YORKSHIRETERRIER,_NO_UCH_SE_UCH_Oxzar_Amazing_Bel%E2%80%99s_Toffy_(24310212305).jpg"
  }
};
